''(
    (section(class: "fl col")
      (h2 a(href: "http://whyso.co.nz/newlook/picturetags") "PictureTags")
      (p "The advanced gallery application.")
      (p "This gallery is made for quickly tagging photos, tagging other tags, browsing photos or tags, importing and exporting groups of photos and tags.")
      (a(href: "http://whyso.co.nz/newlook/picturetags") "More details..."))
    (a(href: "http://market.android.com/details?id=net.flaviusb.picturetags", class: "fr")
      img(src: "http://www.android.com/images/brand/45_avail_market_logo1.png", alt: "Available in Android Market"))
    (div(class: "clear") "")
    (hr)
  )
